version: '3.3'
services:
    cryptobot:
        build: .
        container_name: cryptobot
#        command: python3 CryptoBot.py
        restart: always
#        Will only be needed in the future       
#        ports:
#            - 80:80
        volumes:
            - $PWD:/usr/src/app
        working_dir: 
            - /usr/src/app
